---
title: "ballr: A Package for Analyzing SynTech Servosphere Data"
author: "Jacob T. Wittman"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: /Users/wittm094/Documents/library.bib
vignette: >
  %\VignetteIndexEntry{ballr: A Package for Analyzing SynTech Servosphere Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

A servosphere, or locomotory compensator, is a device that can be used to study
the movement of insects or other small critters. A servosphere is a sphere, on
top of which an insect is placed. A camera pointed at the top of the sphere
watches the insect as it moves and reports position changes to motors positioned
at the base of the ball. As the insect moves, the motors rotate to keep the
insect positioned at the top of the sphere. Locomotory compensators have been
used in a number of studies of insect movement in response to different stimuli
[@Arnold2016; @Becher2009; @Bell1980; @Noldus2002; @Otalora-Luna2011;
@Otalora-Luna2011a; @Otalora-Luna2013; @Party2013; @Sakuma2002].

This package is written specifically to aid with the analysis of data produced
by a SynTech Servosphere [product
website](http://www.ockenfels-syntech.com/products/locomotion-compensation/).
The software provided by with the servosphere can be used for some analyses, but
other, more complicated analyses require working with the raw .csv files
produced during trial recording. This package is the result of my own work
analyzing servosphere data in R for my Master's thesis in the Forest Entomology
lab of the Entomology Department at the University of Minnesota. This short
vignette will describe the .csv output available from the servosphere software
and provide examples of potential work flows for these data.

## Raw Servosphere Data

After each trial recorded by the servosphere, the user can (and should) save the recorded .csv file. The first few rows of one of these .csv files will look like this when first imported into R.

```{r}
dat <- read.csv("ballr/inst/ext/317_03212018_servosphere.csv")
```


- Describe servosphere
- Give examples of papers that have used servosphere
- Describe the data output by the servosphere
- Discuss potential experimental designs of interest
- Describe work flow of the package with examples
- Possibilites for expansions?
